export const DRC_COUNTRY = "République démocratique du Congo";

export const COUNTRY_OPTIONS = [
  DRC_COUNTRY,
  "Angola",
  "Belgique",
  "Burundi",
  "Cameroun",
  "Canada",
  "Congo-Brazzaville",
  "Côte d’Ivoire",
  "France",
  "Gabon",
  "Kenya",
  "Luxembourg",
  "Maurice",
  "Rwanda",
  "Sénégal",
  "Tanzanie",
  "Ouganda",
  "Zambie",
  "Zimbabwe",
] as const;

export const DRC_PROVINCES = [
  "Bas-Uélé",
  "Équateur",
  "Haut-Katanga",
  "Haut-Lomami",
  "Haut-Uélé",
  "Ituri",
  "Kasaï",
  "Kasaï-Central",
  "Kasaï-Oriental",
  "Kinshasa",
  "Kongo-Central",
  "Kwango",
  "Kwilu",
  "Lomami",
  "Lualaba",
  "Mai-Ndombe",
  "Maniema",
  "Mongala",
  "Nord-Kivu",
  "Nord-Ubangi",
  "Sankuru",
  "Sud-Kivu",
  "Sud-Ubangi",
  "Tanganyika",
  "Tshopo",
  "Tshuapa",
] as const;
